targets:
  $default:
    builders:
      json_serializable|json_serializable:
        generate_for:
          - "**/application/**.dart"
      freezed|freezed:
        generate_for:
          - "**/application/**.dart"
      retrofit_generator|retrofit:
        generate_for:
          - "**/application/repository/**.dart"
      auto_route_generator|autoRouteGenerator:
        generate_for:
          - "**/presentation/routes/**.dart"
      riverpod_generator:
        generate_for:
          - "**/application/provider/**.dart"